export const Auth = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
}

export const Feed = {
  ADD_FEED_SUCCESS: 'ADD_FEED_SUCCESS',
  ADD_FEED_ERROR: 'ADD_FEED_ERROR',
  UPDATE_FEED_ERROR: 'UPDATE_FEED_ERROR',
  UPDATE_FEED_SUCCESS: 'UPDATE_FEED_SUCCESS',
  DELETE_FEED_SUCCESS: 'DELETE_FEED_SUCCESS',
  DELETE_FEED_ERROR: 'DELETE_FEED_ERROR',
  FEEDS_SUCCESS: 'FEEDS_SUCCESS',
  FEEDS_ERROR: 'FEEDS_ERROR',
}